version: "3"
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=abdi
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
      - REDIS_URL=redis
      - REDIS_PORT=6379
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abdi
      - MONGO_INITDB_ROOT_PASSWORD=password
